# This file has been generated by update.py. Do not edit!
{ lib, buildVimPluginFrom2Nix, fetchFromGitHub, fetchgit }:

{
  neovim-tasks = buildVimPluginFrom2Nix {
    pname = "neovim-tasks";
    version = "2022-09-28";
    src = fetchFromGitHub {
      owner = "shatur";
      repo = "neovim-tasks";
      rev = "d4b683739e4f1b530eb66e0783a1e3dad5e4b21b";
      sha256 = "0bf0x685w42k7fgmz2055n3gn4kcpvzg1das18acla8m4rqify3d";
    };
    meta.homepage = "https://github.com/shatur/neovim-tasks/";
  };

  noice-nvim = buildVimPluginFrom2Nix {
    pname = "noice.nvim";
    version = "2022-10-03";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "noice.nvim";
      rev = "4924d4a8a33ccc00309cee15c8334cfe2b3838aa";
      sha256 = "0d679whkccmf6jndmxq7fznyjvzj9f20fqyxyqs0rg9bszcmcv5x";
    };
    meta.homepage = "https://github.com/folke/noice.nvim/";
  };


}
