name: Update plugins

on:
  schedule:
    - cron: "15 8 * * *"
  workflow_dispatch:

jobs:
  update-plugins:
    runs-on: ubuntu-latest
    name: Update treesitter grammars
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix run .#update-treesitter-grammars -- --out ./nvim-treesitter/generated.nix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: pluginbot
          commit_user_email: pluginbot@users.noreply.github.com
          commit_author: Jason Cox <steel300@gmail.com>
          commit_message: "chore(grammars): auto update treesitter grammars"
          push_options: "--force"
